version: '3.1'
services:
  ch:
    image: yandex/clickhouse-server
    container_name: ch
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - "./chdata:/var/lib/clickhouse yandex/clickhouse-server "
